### ISSUE TITLE
Please use the github releases

### ISSUE THREAD

**Issue by ForsakenHarmony** [tivac/rollup-plugin-sizes#12]

**Comment by tivac** [comment]
Can you expound on what you're looking for a bit more? This project is pretty simple so I'm not super interested in adding a ton of release overhead.

**Comment by ForsakenHarmony** [comment]
Just a basic changelog, you can use i.e. https://github.com/zeit/release

**Comment by tivac** [comment]
[Changelog](https://github.com/tivac/rollup-plugin-sizes/blob/master/CHANGELOG.md)

**Comment by ForsakenHarmony** [comment]
Now just copy paste the to the github release page 🙃
