### ISSUE TITLE
Ongenerate hook is deprecated

### ISSUE THREAD

**Issue by DavidBabel** [tivac/rollup-plugin-sizes#13]
I got this warning : 

```bash
(!) rollup-plugin-sizes plugin: The ongenerate hook used by plugin rollup-plugin-sizes is deprecated. The generateBundle hook should be used instead.
```
May be good to move it to newer version

**Comment by tivac** [comment]
It certainly is! I'm not using this plugin currently so I haven't needed to carve out time to update it to use `rollup@1` APIs. I'd love a PR for it, but if not I'll try to get to it someday here.

**Comment by donut** [comment]
@tivac There's a pull request now. Any chance of merging it?

**Comment by tivac** [comment]
Yes. Published as `rollup-plugin-sizes@1`
