### ISSUE TITLE
Update peerDependency of Rollup

### ISSUE THREAD

**Issue by Ryuno-Ki** [tivac/rollup-plugin-sizes#44]
Hey there!

Thanks for this plugin! It's useful for game jams like js13kgames :-)

One small favour I'd like to ask you for, though.
Could you update the peerDependency of Rollup?
https://github.com/tivac/rollup-plugin-sizes/blob/8bf28ffb7f241f0b407a6e67cc4aed73be660f36/package.json#L38

I've tested, it works with v2 (at least for me).
This would also require a new releast to npm.

Thanks!

**Comment by tivac** [comment]
I'd happily merge a PR and cut a new release.

**Comment by tivac** [comment]
Fixed in #52, not quite released yet though.

**Comment by tivac** [comment]
Released in `rollup-plugin-sizes@1.0.3`
