### ISSUE TITLE
sizes plugin incompatible with rollup v0.60.0

### ISSUE THREAD

**Issue by MichaelRando** [tivac/rollup-plugin-sizes#8]
[!] TypeError: Cannot read property 'modules' of undefined
TypeError: Cannot read property 'modules' of undefined
    at Object.ongenerate (/Users/mscholz/prj/webclient/node_modules/rollup-plugin-sizes/index.js:62:28)
    at /Users/mscholz/prj/webclient/node_modules/rollup/dist/rollup.js:21676:58
    at Array.map (<anonymous>)
    at /Users/mscholz/prj/webclient/node_modules/rollup/dist/rollup.js:21675:34
    at <anonymous>

**Comment by tivac** [comment]
Not surprising, a bunch of the plugin infrastructure changed in `0.60.0`.

I'll try to take a look soon but am not actively using this plugin atm. A PR would be very welcome!

**Comment by hash-bang** [comment]
#9 fixes this issue

**Comment by tivac** [comment]
Fixed in v0.5.1
